### ISSUE TITLE
servers not appearing on sidebar

### ISSUE THREAD

**Issue by anoraktrend** [EnyoYoen/Fast-Discord#10]
no servers visible.
![Screenshot_2022-05-20_23-50-48](https://user-images.githubusercontent.com/19198652/169634317-f340f93f-ddde-4ee5-8365-ef3d3d320537.png)
here's a screenshot of the empty serverlist.

**Comment by anoraktrend** [comment]
it appears that it cannot see the discord construct of server folders presently, but it otherwise works as intended.

**Comment by EnyoYoen** [comment]
This should be fixed in this [commit](https://github.com/EnyoYoen/Fast-Discord/commit/6fb6bd695b8ab2f4d577bbc7660a43a8e33f4d3c), I leave this issue open for a week if the bug is still present
