### ISSUE TITLE
QIODevice::write (QSslSocket): device not open

### ISSUE THREAD

**Issue by txtsd** [EnyoYoen/Fast-Discord#12]
After compiling and trying to run `Fast-Discord`, this is the only output. The main window appears after the account selector, possibly because I configured in the past, but it's empty.

```shell
λ ./Fast-Discord
QIODevice::write (QSslSocket): device not open
```

EDIT:
OS: Archlinux
Equivalent packages of the ones mentioned in the readme are installed.

**Comment by EnyoYoen** [comment]
This should be fixed in [this commit](https://github.com/EnyoYoen/Fast-Discord/commit/3c6ce0c46bd80c20f32b340da3ea68af32e36304). This was happening because Fast-Discord could not load the informations, probably because your authentication token changed, so I added a way to change it

**Comment by txtsd** [comment]
I'll test in the morning and report back.
