### ISSUE TITLE
Changing Appreance > Message Display doesn't update current chat, doesn't reflect current setting

### ISSUE THREAD

**Issue by WhiteHusky** [EnyoYoen/Fast-Discord#15]
Changing the message display doesn't re-render the chat to the current setting, and it seems like it doesn't show the current setting (chat is in compact, but settings say cozy.)

`AUR: fast-discord-git r219.110de79-1`

**Comment by EnyoYoen** [comment]
This should be fixed in [this commit](https://github.com/EnyoYoen/Fast-Discord/commit/aa7e64a62850fd97b9e87f7ded19d9948094e46a).
